spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8
    username: root
    password: liezh
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    time-zone: GMT+8
    joda-date-time-format: "yyyy-MM-dd HH:mm"